# Generated by Django 5.2.17 on 2026-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Our Story', max_length=150)),
                ('subtitle', models.CharField(default='A thoughtfully curated destination for sarees made to celebrate you.', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('story', models.TextField(default='Saree Elegance is a celebration of timeless Indian craftsmanship and modern style. We bring together handloom textures, graceful silk, comfortable cotton and beautiful prints for every celebration, from everyday gatherings to treasured wedding moments.')),
                ('mission', models.TextField(default='Our promise is simple: help you find a saree that feels as special as the occasion you are dressing for, with thoughtful service and quality you can trust.')),
                ('delivery_commitment', models.CharField(default='Fast Delivery', max_length=80)),
                ('support_commitment', models.CharField(default='24/7 Online Support', max_length=80)),
                ('exchange_commitment', models.CharField(default='Fast Exchange', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=150)),
                ('subtitle', models.CharField(default='Clear guidelines for a smooth and transparent shopping experience.', max_length=250)),
                ('content', models.TextField(default='1. About Saree Elegance\nSaree Elegance provides thoughtfully curated sarees and related services through this website.\n\n2. Product information\nProduct images, descriptions, prices and availability may change. Please review the product details before placing an order.\n\n3. Orders and payments\nOrders are confirmed after successful payment or confirmation of cash on delivery. We may contact you to verify order details before dispatch.\n\n4. Delivery\nWe aim to dispatch orders quickly and provide delivery updates through the contact details shared for the order. Delivery timelines may vary by location.\n\n5. Exchanges and returns\nIf you receive a damaged or incorrect item, contact us promptly with your order details. Exchanges or returns are handled according to our quality-check and customer support process.\n\n6. Privacy\nWe use the information you provide to process orders, respond to enquiries and improve your shopping experience. We do not sell your personal information.\n\n7. Contact\nFor questions about an order, product or these terms, please use the Contact Us page to reach our support team.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms and Conditions Page',
                'verbose_name_plural': 'Terms and Conditions Page',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True),
        ),
    ]
