# Generated by Django 6.0.4 on 2026-09-30 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='image_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='saree',
            name='image',
            field=models.ImageField(blank=True, upload_to='sarees/'),
        ),
    ]
