# Generated by Django 6.0.4 on 2026-10-02 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_saree_image_url_alter_saree_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_customer_saree_cart_item',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
