# Generated by Django 6.0.4 on 2026-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_cartitem_unique_customer_saree_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='canonical_base_url',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='og_image',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='twitter_handle',
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_description',
            field=models.TextField(default='Shop beautiful handloom, silk, georgette and cotton sarees online at Saree Elegance. Find timeless weaves for weddings, festivals and everyday celebrations.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_keywords',
            field=models.CharField(default='sarees, online sarees, handloom sarees, silk sarees, cotton sarees, saree online shopping', max_length=255, verbose_name='Meta Keys'),
        ),
    ]
