# Generated by Django 6.0.4 on 2026-10-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_normalise_slashed_order_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='story',
            field=models.TextField(default='Swathi Designers is a celebration of timeless Indian craftsmanship and modern style. We bring together handloom textures, graceful silk, comfortable cotton and beautiful prints for every celebration, from everyday gatherings to treasured wedding moments.'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_description',
            field=models.TextField(default='Shop beautiful handloom, silk, georgette and cotton sarees online at Swathi Designers. Find timeless weaves for weddings, festivals and everyday celebrations.', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_title',
            field=models.CharField(default='Swathi Designers | Handloom, Silk and Cotton Sarees', max_length=160),
        ),
        migrations.AlterField(
            model_name='seo',
            name='site_name',
            field=models.CharField(default='Swathi Designers', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='shop_name',
            field=models.CharField(default='Swathi Designers', max_length=120),
        ),
        migrations.AlterField(
            model_name='termspage',
            name='content',
            field=models.TextField(default='1. About Swathi Designers\nSwathi Designers provides thoughtfully curated sarees and related services through this website.\n\n2. Product information\nProduct images, descriptions, prices and availability may change. Please review the product details before placing an order.\n\n3. Orders and payments\nOrders are confirmed after successful payment or confirmation of cash on delivery. We may contact you to verify order details before dispatch.\n\n4. Delivery\nWe aim to dispatch orders quickly and provide delivery updates through the contact details shared for the order. Delivery timelines may vary by location.\n\n5. Exchanges and returns\nIf you receive a damaged or incorrect item, contact us promptly with your order details. Exchanges or returns are handled according to our quality-check and customer support process.\n\n6. Privacy\nWe use the information you provide to process orders, respond to enquiries and improve your shopping experience. We do not sell your personal information.\n\n7. Contact\nFor questions about an order, product or these terms, please use the Contact Us page to reach our support team.'),
        ),
    ]
