# Generated by Django 6.0.4 on 2026-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_seed_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_keywords',
            field=models.CharField(default='sarees, online sarees, handloom sarees, silk sarees, cotton sarees, saree online shopping', max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_title',
            field=models.CharField(default='Swathi Designers | Handloom, Silk and Cotton Sarees', max_length=160, verbose_name='Meta title'),
        ),
    ]
