# Generated by Django 6.0.4 on 2026-10-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_saree_product_id_alter_seo_default_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='default_page_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Default description'),
        ),
        migrations.AddField(
            model_name='seo',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta title'),
        ),
        migrations.AddField(
            model_name='seo',
            name='page_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_keywords',
            field=models.CharField(default='sarees, online sarees, handloom sarees, silk sarees, cotton sarees, saree online shopping', max_length=255, verbose_name='Meta keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='default_title',
            field=models.CharField(default='Swathi Designers | Handloom, Silk and Cotton Sarees', max_length=160),
        ),
        migrations.AlterField(
            model_name='seo',
            name='google_site_verification',
            field=models.CharField(blank=True, max_length=100, verbose_name='Google site Verification'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
    ]
