# Generated by Django 6.0.4 on 2026-10-05 18:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_seo_default_page_description_seo_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saree',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Optional. Leave blank to use the price as it is. When set between 0 and 100 the price is worked out once as: discount = original amount x this percentage / 100, then final amount = original amount - discount.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='saree',
            name='dispatch_note',
            field=models.CharField(blank=True, default='Ready to ship in 24 hrs', help_text='Dispatch message shown on the saree card, for example Ready to ship in 24 hrs.', max_length=120),
        ),
        migrations.AddField(
            model_name='saree',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
        migrations.AddField(
            model_name='saree',
            name='length',
            field=models.CharField(blank=True, default='6.3 metres (with blouse piece)', help_text='Shown on the saree card, for example 6.3 metres (with blouse piece).', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_shipping_above',
            field=models.DecimalField(decimal_places=2, default=Decimal('999.00'), help_text='Delivery is free at or above this order total, for example 999 makes delivery free from Rs 999.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('79.00'), help_text='Delivery charge applied when the order total is below the free delivery limit.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='saree',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The original amount before any discount. This value is never changed by a discount.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='saree',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
