# Generated by Django 6.0.4 on 2026-10-06 02:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_saree_discount_and_card_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='payment-qr/')),
                ('upi_id', models.CharField(blank=True, help_text='UPI ID used for the automatically generated QR when no image is uploaded.', max_length=120)),
                ('is_active', models.BooleanField(default=True, help_text='Only the newest active code is shown to customers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment QR Code',
                'verbose_name_plural': 'Payment QR Codes',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The amount the customer was asked to pay.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('card', 'Credit / Debit Card'), ('upi', 'UPI'), ('qr', 'QR Code / Scan & Pay'), ('netbanking', 'Net Banking'), ('cod', 'Cash on Delivery')], default='qr', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='UPI reference or UTR number, when the customer has one.', max_length=100)),
                ('screenshot', models.ImageField(upload_to='payment-proofs/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to='store.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_proofs', to='store.order')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Verification',
                'verbose_name_plural': 'Payment Verifications',
                'ordering': ['-submitted_at', '-id'],
            },
        ),
    ]
