# Generated by Django 6.0.4 on 2026-10-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_payment_qr_and_payment_proofs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Payment done'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
