# Generated by Django 6.0.4 on 2026-10-06 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_paymentproof_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='product_id',
            field=models.CharField(db_index=True, help_text='Between 4 and 220 characters, for example SD-SRK-1001.', max_length=220, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
