# Generated by Django 6.0.4 on 2026-10-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_saree_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saree',
            name='product_id',
            field=models.CharField(blank=True, db_index=True, help_text='Between 4 and 220 characters, for example SD-SRK-1001. Required for new products.', max_length=220),
        ),
    ]
