# Generated by Django 5.2.17 on 2026-10-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_seed_navigation_collections'),
        ('store', '0026_alter_saree_product_id'),
    ]

    operations = [
    ]
