# Generated by Django 6.0.4 on 2026-10-06 10:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_merge_20261006_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='saree',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional delivery charge per saree, added to the site delivery fee when applicable.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='saree',
            name='gst_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='GST percentage applied to this saree, from 1 to 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.TextField(blank=True),
        ),
    ]
