# Generated by Django 6.0.4 on 2026-10-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_saree_delivery_charge_alter_saree_gst_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Welcome to Swathi Designers', max_length=160)),
                ('description', models.TextField(default='Step into a thoughtfully curated world of handloom stories, festive silks, and timeless drapes.', max_length=400)),
                ('tagline', models.CharField(default='Your saree story begins here', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login Page Content',
                'verbose_name_plural': 'Login Page Content',
            },
        ),
    ]
