# Generated by Django 5.0.6 on 2026-10-07 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_loginpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpage',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
