# Generated by Django 5.0.6 on 2026-10-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_login_background_paymentproof_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated time'),
        ),
    ]
