# Generated by Django 5.0.6 on 2026-10-07 10:49

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_paymentproof_updated_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='screenshot',
            field=models.ImageField(upload_to='payment-proofs/', validators=[store.validators.validate_payment_image_extension]),
        ),
    ]
