# Generated by Django 5.0.6 on 2026-10-09 13:22

import django.core.validators
import django.db.models.deletion
import store.validators
from decimal import Decimal
from django.db import migrations, models


def seed_product_types(apps, schema_editor):
    ProductType = apps.get_model("store", "ProductType")
    database = schema_editor.connection.alias
    for order, name, slug in (
        (1, "Jewellery", "jewellery"),
        (2, "Handbags", "handbags"),
    ):
        ProductType.objects.using(database).get_or_create(
            slug=slug,
            defaults={"name": name, "order": order, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_populate_missing_saree_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('image', models.ImageField(upload_to='products/', validators=[store.validators.validate_image_extension])),
                ('in_stock', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='saree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.saree'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('cart', 'product'), name='unique_product_per_shopping_cart'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('product__isnull', True), ('saree__isnull', False)), models.Q(('product__isnull', False), ('saree__isnull', True)), _connector='OR'), name='cart_item_has_one_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.producttype'),
        ),
        migrations.RunPython(seed_product_types, migrations.RunPython.noop),
    ]
