# Generated by Django 5.0.6 on 2026-10-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_product_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saree',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
