# Generated by Django 5.0.6 on 2026-10-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_saree_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter letters and numbers only no spaces or special character', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Enter letters and numbers only no spaces or special character', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(help_text='Enter letters and numbers only no spaces or special character', max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='saree',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter letters and numbers only no spaces or special character', max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Enter letters and numbers only no spaces or special character', max_length=150),
        ),
    ]
