from django.urls import path

from .views import (
    about,
    add_to_cart,
    all_products,
    cart_view,
    catalog,
    category_detail,
    checkout,
    contact,
    generate_qr,
    home,
    login_view,
    logout_view,
    order_success,
    payment_verification,
    profile,
    product_detail,
    remove_cart_item,
    remove_from_cart,
    robots_txt,
    saree_detail,
    subcategory_detail,
    terms,
    update_cart_item,
    update_cart,
)

app_name = "store"

urlpatterns = [
    path("robots.txt", robots_txt, name="robots"),
    path("", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile, name="profile"),
    path("home/", home, name="home"),
    path("about/", about, name="about"),
    path("about-us/", about, name="about_us"),
    path("contact/", contact, name="contact"),
    path("contact-us/", contact, name="contact_us"),
    path("terms/", terms, name="terms"),
    path("terms-conditions/", terms, name="terms_conditions"),
    path("catalog/", catalog, name="catalog"),
    path("products/", all_products, name="all_products"),
    path("catalog/<slug:slug>/", category_detail, name="category_detail"),
    path("collections/<slug:category_slug>/<slug:slug>/", subcategory_detail, name="subcategory_detail"),
    path("saree/<slug:slug>/", saree_detail, name="saree_detail"),
    path("product/<slug:slug>/", product_detail, name="product_detail"),
    path("cart/", cart_view, name="cart"),
    path("cart/add/", add_to_cart, name="add_to_cart"),
    path("cart/item/<str:item_type>/<int:item_id>/update/", update_cart_item, name="update_cart_item"),
    path("cart/item/<str:item_type>/<int:item_id>/remove/", remove_cart_item, name="remove_cart_item"),
    path("cart/update/<int:saree_id>/", update_cart, name="update_cart"),
    path("cart/remove/<int:saree_id>/", remove_from_cart, name="remove_from_cart"),
    path("checkout/", checkout, name="checkout"),
    path("payment-verification/", payment_verification, name="payment_verification"),
    path("payment-verification/<order_id:order_id>/", payment_verification, name="payment_verification_order"),
    path("qr.png", generate_qr, name="generate_qr"),
    path("order/<order_id:order_id>/", order_success, name="order_success"),
]