# Generated by Django 6.0.4 on 2026-09-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='banner_image',
        ),
    ]
