# Generated by Django 5.2.17 on 2026-09-25 07:28

from django.db import migrations, models


def create_seo_settings(apps, schema_editor):
    SEO = apps.get_model("store", "SEO")
    if not SEO.objects.exists():
        SEO.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_aboutpage_contactmessage_termspage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Saree Elegance', max_length=120)),
                ('default_title', models.CharField(default='Saree Elegance | Handloom, Silk and Cotton Sarees', max_length=160)),
                ('default_description', models.TextField(default='Shop beautiful handloom, silk, georgette and cotton sarees online at Saree Elegance. Find timeless weaves for weddings, festivals and everyday celebrations.', max_length=160)),
                ('default_keywords', models.CharField(default='sarees, online sarees, handloom sarees, silk sarees, cotton sarees, saree online shopping', max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('twitter_handle', models.CharField(blank=True, max_length=100)),
                ('canonical_base_url', models.URLField(blank=True)),
                ('google_site_verification', models.CharField(blank=True, max_length=100)),
                ('robots_extra', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.RunPython(create_seo_settings, migrations.RunPython.noop),
    ]
