# Generated by Django 6.0.4 on 2026-09-30 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='category',
            name='tier',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('basic', 'Basic')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.customer')),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='store.saree')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'ordering': ['updated_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'saree'), name='unique_customer_saree_cart_item')],
            },
        ),
    ]